services:
  - type: web
    name: ai-friend-api
    env: python
    buildCommand: pip install -r requirements_mac.txt
    startCommand: python api_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free

  - type: web
    name: ai-friend-web
    env: static
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: ./static
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
