services:
  - type: web
    name: ai-friend-companion
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
